labels:
  env: dev
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/jw-develop/eks-blueprints-workloads
    targetRevision: main

  # Thoses default values can be surcharged by Infrastructure as Code
  env: dev
  clusterName: eks-blueprint-cluster # the name of EKS cluster
  blueprint: 'terraform' # cdk | terraform
  karpenterInstanceProfile:
  ingress:
    type: 'alb' # nginx | alb
    # host: dev.example.com
